from pySecDec.amplitude_interface import Configuration, Qmc, CubaIntegrator, ContourDeformation
import os


name = "nonplanar_2L"

# define the integral directory generated by `sum_pacakge`
config = Configuration(name)

integrator = Qmc(transform="korobov3", fitfunction="polysingular")

# set options for the integrals
config.set_options(
                    integrator,
                    ContourDeformation(),
                )
# write the config_name.hpp file
config.configure()
