from pySecDec.amplitude_interface import Configuration, Qmc, CubaIntegrator, ContourDeformation

# define the integral directory generated by `sum_pacakge`
config = Configuration('AA_F3_1_1_1_1_1_1_1_0_0')

# set options for the integrals
config.set_options(
                      CubaIntegrator('Vegas', epsrel=1e-4),
                      ContourDeformation(),
                      sub_integral_name='AA_F3_1_1_1_1_1_1_1_0_0'
                  )
config.set_options(
                      Qmc(transform="korobov3x5"),
                      ContourDeformation(number_of_presamples=1000),
                      sub_integral_name='AA_F1diminc4_0_2_2_1_0_1_0_1_0'
                  )

# write the config_box2L_pp.hpp file
config.configure()
