# Defines variables needed to build the library.
# ----------------------------------------------

# set name of the integral
NAME_I2 = yyyy_bubble
NAME_I4 = yyyy_box6Dim

# common .PHONY variables
.PHONY : compile static dynamic source2 source4 clean very-clean cuba

# set global default goal
.DEFAULT_GOAL = compile

# set default dependencies
compile : static dynamic
static : source2 lib$(NAME_I2).a source4 lib$(NAME_I4).a
dynamic : source2 lib$(NAME_I2).so source4 lib$(NAME_I4).so

# get path to the top level directory
TOPDIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))



# python executable
PYTHON = python



# FORM executable
ifeq (x$(SECDEC_CONTRIB), x)
FORMCMD = tform
else
FORMCMD = $(SECDEC_CONTRIB)/bin/tform
endif

# number of threads when using tform
FORMTHREADS = 2

# global FORM options
FORMOPTIONS = -M -w$(FORMTHREADS)

# call to FORM
FORM = $(FORMCMD) $(FORMOPTIONS)



# c++ compiler
CXX = g++

# c++ compiler flags
CXXFLAGS = -std=c++11 -O2 -I. -I$(TOPDIR)
ifneq (x$(SECDEC_CONTRIB), x)
CXXFLAGS += -I$(SECDEC_CONTRIB)/include
endif

# linker flags
ifeq (x$(SECDEC_CONTRIB), x)
LDFLAGS =
else
LDFLAGS = -L$(SECDEC_CONTRIB)/lib
endif
LDFLAGS += -L$(TOPDIR) -l$(NAME_I2) -l$(NAME_I4) -lgsl -lgslcblas -lcuba -lm

# implicit rules to build object files
%.static.o : %.cpp
	$(CXX) -c $(CXXFLAGS) $< -o $@
%.dynamic.o : %.cpp
	$(CXX) -c $(CXXFLAGS) -fPIC $< -o $@
