from pySecDec.amplitude_interface import Configuration, Qmc, CubaIntegrator, ContourDeformation
from os.path import isdir

for name in "bubble2L_smallm":
    if not isdir(name):
        continue
    # give the integral directory generated by `sum_pacakge`
    config = Configuration(name)

    # set options for the integrals
    config.set_options(
                        Qmc(transform="korobov3", fitfunction="polysingular"),
                        ContourDeformation(),
                    )

    # write the config_name.hpp file
    config.configure()
