from pySecDec.amplitude_interface import Configuration, Qmc, CubaIntegrator, ContourDeformation
import os

for name in "box2L_big_loop_massive_expansion_by_regions", "box2L_small_loop_massive_expansion_by_regions":
    if not os.path.isdir(name):
        continue
    # define the integral directory generated by `sum_pacakge`
    config = Configuration(name)

    # set options for the integrals
    config.set_options(
                        Qmc(transform="korobov3", fitfunction="polysingular"),
                        ContourDeformation(),
                    )

    # write the config_name.hpp file
    config.configure()
