.DEFAULT_GOAL = test

# get path to the top level directory
TEST_FRAMEWORK_DIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
EXAMPLES_DIR = $(TEST_FRAMEWORK_DIR)/..

SECDEC_CONTRIB = $(shell python3 -m pySecDecContrib --dirname)

CXX ?= g++
CXXFLAGS = -std=c++11 -I$(TEST_FRAMEWORK_DIR) -I$(SECDEC_CONTRIB)/include
LDFLAGS = -L$(SECDEC_CONTRIB)/lib
ifdef SECDEC_WITH_CUDA
CXXFLAGS += -DSECDEC_WITH_CUDA=$(SECDEC_WITH_CUDA) -x cu -arch=$(SECDEC_WITH_CUDA)
LDFLAGS += -arch=$(SECDEC_WITH_CUDA)
else
LDFLAGS += -pthread
endif
LDFLAGS += -L$(TEST_FRAMEWORK_DIR) -lgsl -lgslcblas -lcuba -lm


PYTHON ?= python3
