# Defines variables needed to build the library.
# ----------------------------------------------

# enables debugging flags
# export DEBUG = 1

# set name of the integral
NAME = %(name)s

# common .PHONY variables
.PHONY : static dynamic pylink source clean very-clean

# set global default goal
.DEFAULT_GOAL = pylink

# define file-aliasing .PHONY targets
static : lib$(NAME).a
dynamic : lib$(NAME).so
pylink : $(NAME)_pylink.so

# get path to the top level directory
TOPDIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))



# python executable
PYTHON ?= python3

SECDEC_CONTRIB = %(contrib_dirname)s

# FORM executable
FORM ?= "$(SECDEC_CONTRIB)/bin/tform"

# number of threads when using tform
FORMTHREADS ?= %(form_threads)i

# FORM code optimization level
FORMOPT ?= %(form_optimization_level)i

# call to FORM
FORMCALL = $(FORM) -M -w$(FORMTHREADS) -D optimizationLevel=$(FORMOPT)



# c++ compiler
CXX ?= g++

# Maintain old behaviour of SECDEC_WITH_CUDA if SECDEC_WITH_CUDA is defined and SECDEC_WITH_CUDA_FLAGS is not defined
ifdef SECDEC_WITH_CUDA
SECDEC_WITH_CUDA_FLAGS ?= -arch=${SECDEC_WITH_CUDA}
endif

# c++ compiler flags
ifeq ($(DEBUG),1)
ifdef SECDEC_WITH_CUDA_FLAGS
CXXFLAGS = -Xcompiler "-O0 -ggdb3 -fsanitize=address -fno-omit-frame-pointer"
else
CXXFLAGS = -O0 -ggdb3 -fsanitize=address -fno-omit-frame-pointer
endif
else
CXXFLAGS = -O2
endif
CXXFLAGS += -std=c++14 -I. -I$(TOPDIR)
CXXFLAGS += -I"$(SECDEC_CONTRIB)/include"
ifdef SECDEC_WITH_CUDA_FLAGS
CXXFLAGS += -x cu $(SECDEC_WITH_CUDA_FLAGS) -DSECDEC_WITH_CUDA
endif

# linker flags
ifeq ($(DEBUG),1)
LDFLAGS = -g -fsanitize=address -L"$(SECDEC_CONTRIB)/lib"
else
LDFLAGS = -L"$(SECDEC_CONTRIB)/lib"
endif
ifdef SECDEC_WITH_CUDA_FLAGS
LDFLAGS += $(SECDEC_WITH_CUDA_FLAGS)
else
LDFLAGS += -pthread
endif
LDFLAGS += -L$(TOPDIR) -lgsl -lgslcblas -lcuba -lm

