name: Fast Check
on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Make Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [self-hosted]

    steps:
    - name: Install dependencies
      run: |
        if ! dpkg -s graphviz normaliz nauty libgsl-dev; then
          sudo apt-get update
          sudo apt-get install -y graphviz normaliz nauty libgsl-dev
        fi

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Setup environment variables
      run: |
        echo "PYTHON=/runner/_work/_tool/Python/3.8.18/x64/bin/python3.8" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/runner/_work/_tool/Python/3.8.18/x64/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        make dependencies

    - name: Verify Python Installation 1
      run: |
        which python3.8
        echo $PATH
        which sphinx-build
        sphinx-build --version
        python3.8 --version

    - name: Build
      run: |
        make build

    - name: pytest Check
      run: |
        python3 -m pytest --timeout=600 pySecDec

    - name: Verify Python Installation
      run: |
        which python3.8
        echo $PATH
        which sphinx-build
        python3.8 --version
        ls -l /runner/_work/_tool/Python/3.8.18/x64/lib/

    - name: Doc Test
      run: |
        export LD_LIBRARY_PATH=/runner/_work/_tool/Python/3.8.18/x64/lib:$LD_LIBRARY_PATH
        PYTHON=/runner/_work/_tool/Python/3.8.18/x64/bin/python3.8 make doctest

    - name: Util Check
      run: |
        make util-check -j2

    - name: High-level Tests
      run: |
        make -C high_level_tests runselected -j2

    - name: High-level Test Summary
      run: |
        make -C high_level_tests summarize-selected
