name: Fast Check

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Make Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [self-hosted]

    steps:
      # 🔥 Nuke ~/.local to avoid ghost binaries and old pip installs
      - name: Nuke ~/.local
        run: |
          echo "Removing ~/.local to avoid leftover binaries from older workflows..."
          rm -rf ~/.local

      # ✅ Checkout Repo
      - uses: actions/checkout@v3

      # ✅ Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      # ✅ Confirm Python version and path
      - name: Verify Python setup
        run: |
          which python3
          python3 --version
          which pip
          pip --version

      # ✅ Set Environment Variables
      - name: Setup environment variables
        run: |
          PY_DIR=$(dirname $(dirname $(which python3)))
          echo "PYTHON=$PY_DIR/bin/python3" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$PY_DIR/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # ✅ Install Python dependencies
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx
          make dependencies

      # ✅ Confirm sphinx-build is using correct Python
      - name: Debug sphinx-build
        run: |
          which sphinx-build
          head -n 1 $(which sphinx-build)
          sphinx-build --version

      # ✅ Build
      - name: Build
        run: |
          make build

      # ✅ Run Unit Tests
      - name: Run pytest
        run: |
          python3 -m pytest --timeout=600 pySecDec

      # ✅ Verify Python Installation and Library Paths
      - name: Verify Python Libs
        run: |
          python3 --version
          echo $LD_LIBRARY_PATH
          ls -l $(dirname $(dirname $(which python3)))/lib/

      # ✅ Run Doc Tests
      - name: Doc Test
        run: |
          PYTHON=$(which python3)
          export LD_LIBRARY_PATH=$(dirname $(dirname $PYTHON))/lib:$LD_LIBRARY_PATH
          PYTHON=$PYTHON make doctest

      # ✅ Utility Check
      - name: Util Check
        run: |
          make util-check -j2

      # ✅ High-Level Tests
      - name: High-level Tests
        run: |
          make -C high_level_tests runselected -j2

      # ✅ High-Level Test Summary
      - name: High-level Test Summary
        run: |
          make -C high_level_tests summarize-selected
